apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deploy.yaml
  - service.yaml

images:
  - name: rag-api
    newName: ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/rag-api
    newTag: 2c9b4c2
